/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BiggiveArticleCard {
        /**
          * Card background colour
         */
        "backgroundColour": string;
        /**
          * Card background colour hover
         */
        "backgroundColourHover": string;
        /**
          * Button label
         */
        "buttonLabel": string;
        /**
          * Button URL
         */
        "buttonUrl": string;
        /**
          * Date
         */
        "date": string;
        /**
          * Image Alt Text
         */
        "imageAltText": string;
        /**
          * Image Label
         */
        "imageLabel": string;
        /**
          * Image URL
         */
        "imageUrl": string;
        /**
          * Main title
         */
        "mainTitle": string;
        /**
          * Slug
         */
        "slug": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Text colour
         */
        "textColour": string;
    }
    interface BiggiveBackToTop {
    }
    interface BiggiveBasicCard {
        /**
          * Background colour.
         */
        "backgroundColour": string;
        /**
          * Full URL of the background image.
         */
        "backgroundImageUrl": string;
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme": string;
        /**
          * Button label
         */
        "buttonLabel": string;
        /**
          * Button URL
         */
        "buttonUrl": string;
        /**
          * Card colour
         */
        "cardColour": string;
        /**
          * Clip bottom left corner
         */
        "clipBottomLeftCorner": boolean;
        /**
          * Clip top right corner
         */
        "clipTopRightCorner": boolean;
        "headingLevel": 1 | 2 | 3 | 4 | 5 | 6;
        /**
          * Icon
         */
        "icon": boolean;
        /**
          * Icon colour
         */
        "iconColour": string;
        /**
          * Main title
         */
        "mainTitle": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Subtitle title
         */
        "subtitle": string;
        /**
          * Teaser
         */
        "teaser": string;
        /**
          * Text colour
         */
        "textColour": string;
    }
    interface BiggiveBeneficiaryIcon {
        /**
          * Background colour
         */
        "backgroundColour": string;
        /**
          * Icon
         */
        "icon": string;
        /**
          * Background colour
         */
        "iconColour": string;
        /**
          * Label
         */
        "label": string;
        /**
          * Url
         */
        "url": string;
    }
    interface BiggiveBiographyCard {
        /**
          * Job title
         */
        "fullName": string;
        /**
          * Full URL of the main image.
         */
        "imageUrl": string;
        /**
          * Job title
         */
        "jobTitle": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveBoxedContent {
        /**
          * Background colour
         */
        "backgroundColour": string;
        /**
          * Horizontal padding
         */
        "horizontalPadding": number;
        /**
          * Shadow
         */
        "shadow": boolean;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Vertical padding
         */
        "verticalPadding": number;
    }
    interface BiggiveBrandedImage {
        /**
          * Charity location
         */
        "charityLocation": string;
        /**
          * Charity name
         */
        "charityName": string;
        /**
          * Link to the charity's website
         */
        "charityUrl": string;
        /**
          * Full URL of a image.
         */
        "imageUrl": string;
        /**
          * Full URL of the logo.
         */
        "logoUrl": string;
        /**
          * Slug
         */
        "slug": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveButton {
        /**
          * Centered
         */
        "centered": boolean;
        /**
          * Colour Scheme
         */
        "colourScheme": string;
        /**
          * Display full width
         */
        "fullWidth": boolean;
        /**
          * Text
         */
        "label": string;
        /**
          * New Tab
         */
        "openInNewTab": boolean;
        /**
          * Rounded corners
         */
        "rounded": boolean;
        /**
          * Size
         */
        "size": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * URL
         */
        "url": string;
    }
    interface BiggiveCallToAction {
        /**
          * Default text colour
         */
        "defaultTextColour": string;
        /**
          * Main title
         */
        "mainTitle": string;
        /**
          * Main title colour
         */
        "mainTitleColour": string;
        /**
          * Main title size
         */
        "mainTitleSize": number;
        /**
          * Primary button Colour Scheme
         */
        "primaryButtonColourScheme": string;
        /**
          * Primary button Label
         */
        "primaryButtonLabel": string;
        /**
          * Primary button Url
         */
        "primaryButtonUrl": string;
        /**
          * Secondary button Colour Scheme
         */
        "secondaryButtonColourScheme": string;
        /**
          * Secondary button Label
         */
        "secondaryButtonLabel": string;
        /**
          * Secondary button Url
         */
        "secondaryButtonUrl": string;
        /**
          * Slug
         */
        "slug": string;
        /**
          * Slug colour
         */
        "slugColour": string;
        /**
          * Slug size
         */
        "slugSize": number;
        /**
          * Space above component
         */
        "spaceAbove": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Subtitle
         */
        "subtitle": string;
        /**
          * Subtitle colour
         */
        "subtitleColour": string;
        /**
          * Main title size
         */
        "subtitleSize": number;
        /**
          * Teaser
         */
        "teaser": string;
        /**
          * Teaser colour
         */
        "teaserColour": string;
    }
    interface BiggiveCampaignCard {
        /**
          * Full URL of a banner image.
         */
        "banner": string;
        /**
          * Display name of the charity's specific time-bound fundraising campaign.
         */
        "campaignTitle": string;
        /**
          * e.g. "Match Funded".
         */
        "campaignType": string;
        /**
          * To be used alongside isFutureCampaign = true or isPastCampaign = true. If either is true, we render out: 'Launches: ' + datetime or 'Closed: ' + datetime. Preferred format: DD/MM/YYYY, HH:MM DON-661.
         */
        "datetime": string;
        /**
          * Donate button colour scheme
         */
        "donateButtonColourScheme": string;
        /**
          * Donate button label
         */
        "donateButtonLabel": string;
        /**
          * Donate button url
         */
        "donateButtonUrl": string;
        /**
          * Boolean flag telling the component if the campaign is in the future (not open yet).
         */
        "isFutureCampaign": boolean;
        /**
          * Boolean flag telling the component if the campaign is in the future (not open yet).
         */
        "isPastCampaign": boolean;
        /**
          * Donate button colour scheme
         */
        "moreInfoButtonColourScheme": string;
        /**
          * More information button label
         */
        "moreInfoButtonLabel": string;
        /**
          * More information button url
         */
        "moreInfoButtonUrl": string;
        /**
          * Display name of the charity or non-profit.
         */
        "organisationName": string;
        /**
          * Amount for the primary figure, formatted with currency symbol
         */
        "primaryFigureAmount": string;
        /**
          * Label for the primary figure
         */
        "primaryFigureLabel": string;
        /**
          * Progress bar percentage
         */
        "progressBarCounter": number;
        /**
          * Amount for the secondary figure, formatted with currency symbol
         */
        "secondaryFigureAmount": string;
        /**
          * Label for the secondary figure
         */
        "secondaryFigureLabel": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveCampaignCardFilterGrid {
        /**
          * JSON array of beneficiary key/values, or takes a stringified equiavalent (for Storybook)
         */
        "beneficiaryOptions": string | string[];
        /**
          * Defines the text on the search button
         */
        "buttonText": string;
        /**
          * JSON array of category key/values, or takes a stringified equiavalent (for Storybook)
         */
        "categoryOptions": string | string[];
        /**
          * JSON array of funding key/values, or takes a stringified equiavalent (for Storybook)
         */
        "fundingOptions": string | string[];
        /**
          * Intro
         */
        "intro": string;
        /**
          * JSON array of location key/values, or takes a stringified equiavalent (for Storybook)
         */
        "locationOptions": string | string[];
        /**
          * Defines the text displayed as the placeholder in the input field before the user types anything
         */
        "placeholderText": string;
        /**
          * Optional search text prop. Useful for pre-populating the search field when the page is loaded with a search term already existing in the URL. This can happen when sharing links, or if a donor goes to a campaign page after searching, and then returns to the search results. In such a case, the search box text will clear, unless we use this prop to populate it on rendering. DON-652.
         */
        "searchText": string | null;
        /**
          * For injecting the chosen beneficiary to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterBeneficiary": string | null;
        /**
          * For injecting the chosen category to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterCategory": string | null;
        /**
          * For injecting the chosen funding to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterFunding": string | null;
        /**
          * For injecting the chosen location to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterLocation": string | null;
        /**
          * This helps us inject a pre-selected dropdown value from outside of this component. This is especially helpful for the Meta campaign and Explore pages, where searching by text whipes out previous sort options and re-uses Relevance, or where one of those two pages is loaded directly with URL parameters - in such a scenario the dropdown shows that it's pre-selected. DON-558.
         */
        "selectedSortByOption": 'Most raised' | 'Match funds remaining' | 'Relevance' | null;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveCampaignHighlights {
        /**
          * Full URL of a banner image.
         */
        "banner": string;
        /**
          * Display name of the charity's specific time-bound fundraising campaign.
         */
        "campaignTitle": string;
        /**
          * Champion's name
         */
        "championName": string;
        /**
          * Link to all meta-campaigns funded by this champion. For example: /christmas-challenge-2022/the-reed-foundation-22 In other words, it follows the following format: '/' + campaign.parentRef + '/' + campaign.championRef
         */
        "championUrl": string;
        /**
          * Amount for the primary figure, formatted with currency symbol
         */
        "primaryFigureAmount": string;
        /**
          * Label for the primary figure
         */
        "primaryFigureLabel": string;
        /**
          * Primary stat icon
         */
        "primaryStatIcon": string;
        /**
          * Primary stat text
         */
        "primaryStatText": string;
        /**
          * Progress bar percentage
         */
        "progressBarCounter": number;
        /**
          * Amount for the secondary figure, formatted with currency symbol
         */
        "secondaryFigureAmount": string;
        /**
          * Label for the secondary figure
         */
        "secondaryFigureLabel": string;
        /**
          * Secondary stat icon
         */
        "secondaryStatIcon": string;
        /**
          * Secondary stat text
         */
        "secondaryStatText": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveCategoryIcon {
        /**
          * Background colour
         */
        "backgroundColour": string;
        /**
          * Icon
         */
        "icon": string;
        /**
          * Background colour
         */
        "iconColour": string;
        /**
          * Label
         */
        "label": string;
        /**
          * Url
         */
        "url": string;
    }
    interface BiggiveFooter {
        "headingLevel": 1 | 2 | 3 | 4 | 5 | 6;
    }
    interface BiggiveForm {
    }
    interface BiggiveFormFieldSelect {
        /**
          * Placeholder
         */
        "placeholder": string;
        "selectedLabel": string | null;
        "selectedValue": string | null;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveFormFieldSelectOption {
        /**
          * Label
         */
        "label": string;
        /**
          * Value
         */
        "value": string;
    }
    interface BiggiveFormattedText {
        /**
          * Default text colour
         */
        "defaultTextColour": string;
        /**
          * Width
         */
        "maxWidth": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveGrid {
        /**
          * Number of columns in grid
         */
        "columnCount": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Should have `justify-content: space-between`?
         */
        "spaceBetween": boolean;
    }
    interface BiggiveHeader {
        "closeMenuFromOutside": () => Promise<void>;
        /**
          * Logo hyperlink URL
         */
        "logoUrl": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveHeading {
        /**
          * Text alignment
         */
        "align": string;
        /**
          * Colour Scheme
         */
        "colour": string;
        /**
          * HTML element
         */
        "htmlElement": string;
        /**
          * Icon
         */
        "icon": boolean;
        /**
          * Icon colour
         */
        "iconColour": string;
        /**
          * Heading size
         */
        "size": number;
        /**
          * Space above component
         */
        "spaceAbove": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Heading text
         */
        "text": string;
    }
    interface BiggiveHeroImage {
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme": string;
        /**
          * Button Label
         */
        "buttonLabel": string;
        /**
          * Button Url
         */
        "buttonUrl": string;
        /**
          * Colour Scheme
         */
        "colourScheme": string;
        /**
          * Full URL of a logo image.
         */
        "logo": string;
        /**
          * Logo alt text
         */
        "logoAltText": string;
        /**
          * Full URL of a main hero image.
         */
        "mainImage": string|null;
        /**
          * Horizontal alignment of image
         */
        "mainImageAlignHorizontal": string;
        /**
          * Vertical alignment of image
         */
        "mainImageAlignVertical": string;
        /**
          * Hero image title, typically the page.
         */
        "mainTitle": string;
        /**
          * Main title colour
         */
        "mainTitleColour": string;
        /**
          * Header slug
         */
        "slug": string;
        /**
          * Header slug colour
         */
        "slugColour": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Introductory teaser text
         */
        "teaser": string;
        /**
          * Teaser colour
         */
        "teaserColour": string;
    }
    interface BiggiveIconGroup {
        /**
          * Label
         */
        "label": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveImage {
        /**
          * Image width
         */
        "height": number;
        /**
          * Image alt text tag.
         */
        "imageAltText": string;
        /**
          * Full URL of a image.
         */
        "imageUrl": string;
        /**
          * Size unit
         */
        "sizeUnit": string;
        /**
          * Space above component
         */
        "spaceAbove": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Image width
         */
        "width": number;
    }
    interface BiggiveImageFeature {
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme": string;
        /**
          * Button Label
         */
        "buttonLabel": string;
        /**
          * Button Url
         */
        "buttonUrl": string;
        /**
          * Default text colour
         */
        "defaultTextColour": string;
        /**
          * Image alt text tag.
         */
        "imageAltText": string;
        /**
          * Full URL of a image.
         */
        "imageUrl": string;
        /**
          * Video title
         */
        "mainTitle": string;
        /**
          * Slug colour
         */
        "mainTitleColour": string;
        /**
          * Slug
         */
        "slug": string;
        /**
          * Slug colour
         */
        "slugColour": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Introductory teaser text
         */
        "teaser": string;
        /**
          * Teaser colour
         */
        "teaserColour": string;
    }
    interface BiggiveMainMenu {
        "closeMobileMenuFromOutside": () => Promise<void>;
    }
    interface BiggiveMiscIcon {
        /**
          * Background colour
         */
        "backgroundColour": string;
        /**
          * Icon
         */
        "icon": string;
        /**
          * Background colour
         */
        "iconColour": string;
        /**
          * Url
         */
        "url": string;
    }
    interface BiggiveNavGroup {
        /**
          * Inline
         */
        "inline": boolean;
    }
    interface BiggiveNavItem {
        /**
          * URL
         */
        "iconColour": string;
        /**
          * Label
         */
        "label": string;
        /**
          * URL
         */
        "url": string;
    }
    interface BiggivePageColumn {
    }
    interface BiggivePageColumns {
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggivePageSection {
        /**
          * Colour scheme
         */
        "colourScheme": string;
        /**
          * Width
         */
        "maxWidth": number;
        /**
          * Section style bottom
         */
        "sectionStyleBottom": string;
        /**
          * Section style top
         */
        "sectionStyleTop": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggivePopup {
        "closeFromOutside": () => Promise<void>;
        "openFromOutside": () => Promise<void>;
    }
    interface BiggivePopupStandalone {
    }
    interface BiggiveProgressBar {
        /**
          * Colour Scheme
         */
        "colourScheme": string;
        /**
          * Percentage to show + use for CSS width; round before input if desired
         */
        "counter": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveQuote {
        /**
          * Attribution text
         */
        "attribution": string;
        /**
          * Default text colour
         */
        "defaultTextColour": string;
        /**
          * Quote text
         */
        "quote": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    /**
     * @deprecated (?) I don't think Donate is using this. Unless there is a WordPress use case,
     * should we delete it rather than maintaining?
     */
    interface BiggiveSearch {
        /**
          * Defines the text on the search button
         */
        "buttonText": string;
        /**
          * Defines the text displayed as the placeholder in the input field before the user types anything
         */
        "placeholderText": string;
        "searchText": string;
    }
    interface BiggiveSocialIcon {
        /**
          * Background colour
         */
        "backgroundColour": string;
        /**
          * Icon colour
         */
        "iconColour": string;
        /**
          * Service name
         */
        "service": string;
        /**
          * Url
         */
        "url": string;
    }
    interface BiggiveTab {
        /**
          * Title
         */
        "tabTitle": string;
    }
    interface BiggiveTabbedContent {
        /**
          * Default text colour
         */
        "defaultTextColour": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveTextInput {
    }
    interface BiggiveTotalizer {
        /**
          * Primary message
         */
        "mainMessage": string;
        /**
          * Primary banner colour
         */
        "primaryColour": string;
        /**
          * Primary text colour
         */
        "primaryTextColour": string;
        /**
          * Secondary banner colour
         */
        "secondaryColour": string;
        /**
          * Secondary text colour
         */
        "secondaryTextColour": string;
        /**
          * Space below component
         */
        "spaceBelow": number;
    }
    interface BiggiveTotalizerTickerItem {
        /**
          * Figure
         */
        "figure": string;
        /**
          * Figure
         */
        "label": string;
    }
    interface BiggiveVideo {
        /**
          * Space above component
         */
        "spaceAbove": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Full URL of a video.
         */
        "videoUrl": string;
    }
    interface BiggiveVideoFeature {
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme": string;
        /**
          * Button Label
         */
        "buttonLabel": string;
        /**
          * Button Url
         */
        "buttonUrl": string;
        /**
          * Default text colour
         */
        "defaultTextColour": string;
        /**
          * Video title
         */
        "mainTitle": string;
        /**
          * Slug colour
         */
        "mainTitleColour": string;
        /**
          * Slug
         */
        "slug": string;
        /**
          * Slug colour
         */
        "slugColour": string;
        /**
          * Space above component
         */
        "spaceAbove": number;
        /**
          * Space below component
         */
        "spaceBelow": number;
        /**
          * Introductory teaser text
         */
        "teaser": string;
        /**
          * Teaser colour
         */
        "teaserColour": string;
        /**
          * Full URL of a video.
         */
        "videoUrl": string;
    }
}
export interface BiggiveButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBiggiveButtonElement;
}
export interface BiggiveCampaignCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBiggiveCampaignCardElement;
}
export interface BiggiveCampaignCardFilterGridCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBiggiveCampaignCardFilterGridElement;
}
export interface BiggiveFormFieldSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBiggiveFormFieldSelectElement;
}
export interface BiggiveFormFieldSelectOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBiggiveFormFieldSelectOptionElement;
}
export interface BiggiveSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBiggiveSearchElement;
}
declare global {
    interface HTMLBiggiveArticleCardElement extends Components.BiggiveArticleCard, HTMLStencilElement {
    }
    var HTMLBiggiveArticleCardElement: {
        prototype: HTMLBiggiveArticleCardElement;
        new (): HTMLBiggiveArticleCardElement;
    };
    interface HTMLBiggiveBackToTopElement extends Components.BiggiveBackToTop, HTMLStencilElement {
    }
    var HTMLBiggiveBackToTopElement: {
        prototype: HTMLBiggiveBackToTopElement;
        new (): HTMLBiggiveBackToTopElement;
    };
    interface HTMLBiggiveBasicCardElement extends Components.BiggiveBasicCard, HTMLStencilElement {
    }
    var HTMLBiggiveBasicCardElement: {
        prototype: HTMLBiggiveBasicCardElement;
        new (): HTMLBiggiveBasicCardElement;
    };
    interface HTMLBiggiveBeneficiaryIconElement extends Components.BiggiveBeneficiaryIcon, HTMLStencilElement {
    }
    var HTMLBiggiveBeneficiaryIconElement: {
        prototype: HTMLBiggiveBeneficiaryIconElement;
        new (): HTMLBiggiveBeneficiaryIconElement;
    };
    interface HTMLBiggiveBiographyCardElement extends Components.BiggiveBiographyCard, HTMLStencilElement {
    }
    var HTMLBiggiveBiographyCardElement: {
        prototype: HTMLBiggiveBiographyCardElement;
        new (): HTMLBiggiveBiographyCardElement;
    };
    interface HTMLBiggiveBoxedContentElement extends Components.BiggiveBoxedContent, HTMLStencilElement {
    }
    var HTMLBiggiveBoxedContentElement: {
        prototype: HTMLBiggiveBoxedContentElement;
        new (): HTMLBiggiveBoxedContentElement;
    };
    interface HTMLBiggiveBrandedImageElement extends Components.BiggiveBrandedImage, HTMLStencilElement {
    }
    var HTMLBiggiveBrandedImageElement: {
        prototype: HTMLBiggiveBrandedImageElement;
        new (): HTMLBiggiveBrandedImageElement;
    };
    interface HTMLBiggiveButtonElement extends Components.BiggiveButton, HTMLStencilElement {
    }
    var HTMLBiggiveButtonElement: {
        prototype: HTMLBiggiveButtonElement;
        new (): HTMLBiggiveButtonElement;
    };
    interface HTMLBiggiveCallToActionElement extends Components.BiggiveCallToAction, HTMLStencilElement {
    }
    var HTMLBiggiveCallToActionElement: {
        prototype: HTMLBiggiveCallToActionElement;
        new (): HTMLBiggiveCallToActionElement;
    };
    interface HTMLBiggiveCampaignCardElement extends Components.BiggiveCampaignCard, HTMLStencilElement {
    }
    var HTMLBiggiveCampaignCardElement: {
        prototype: HTMLBiggiveCampaignCardElement;
        new (): HTMLBiggiveCampaignCardElement;
    };
    interface HTMLBiggiveCampaignCardFilterGridElement extends Components.BiggiveCampaignCardFilterGrid, HTMLStencilElement {
    }
    var HTMLBiggiveCampaignCardFilterGridElement: {
        prototype: HTMLBiggiveCampaignCardFilterGridElement;
        new (): HTMLBiggiveCampaignCardFilterGridElement;
    };
    interface HTMLBiggiveCampaignHighlightsElement extends Components.BiggiveCampaignHighlights, HTMLStencilElement {
    }
    var HTMLBiggiveCampaignHighlightsElement: {
        prototype: HTMLBiggiveCampaignHighlightsElement;
        new (): HTMLBiggiveCampaignHighlightsElement;
    };
    interface HTMLBiggiveCategoryIconElement extends Components.BiggiveCategoryIcon, HTMLStencilElement {
    }
    var HTMLBiggiveCategoryIconElement: {
        prototype: HTMLBiggiveCategoryIconElement;
        new (): HTMLBiggiveCategoryIconElement;
    };
    interface HTMLBiggiveFooterElement extends Components.BiggiveFooter, HTMLStencilElement {
    }
    var HTMLBiggiveFooterElement: {
        prototype: HTMLBiggiveFooterElement;
        new (): HTMLBiggiveFooterElement;
    };
    interface HTMLBiggiveFormElement extends Components.BiggiveForm, HTMLStencilElement {
    }
    var HTMLBiggiveFormElement: {
        prototype: HTMLBiggiveFormElement;
        new (): HTMLBiggiveFormElement;
    };
    interface HTMLBiggiveFormFieldSelectElement extends Components.BiggiveFormFieldSelect, HTMLStencilElement {
    }
    var HTMLBiggiveFormFieldSelectElement: {
        prototype: HTMLBiggiveFormFieldSelectElement;
        new (): HTMLBiggiveFormFieldSelectElement;
    };
    interface HTMLBiggiveFormFieldSelectOptionElement extends Components.BiggiveFormFieldSelectOption, HTMLStencilElement {
    }
    var HTMLBiggiveFormFieldSelectOptionElement: {
        prototype: HTMLBiggiveFormFieldSelectOptionElement;
        new (): HTMLBiggiveFormFieldSelectOptionElement;
    };
    interface HTMLBiggiveFormattedTextElement extends Components.BiggiveFormattedText, HTMLStencilElement {
    }
    var HTMLBiggiveFormattedTextElement: {
        prototype: HTMLBiggiveFormattedTextElement;
        new (): HTMLBiggiveFormattedTextElement;
    };
    interface HTMLBiggiveGridElement extends Components.BiggiveGrid, HTMLStencilElement {
    }
    var HTMLBiggiveGridElement: {
        prototype: HTMLBiggiveGridElement;
        new (): HTMLBiggiveGridElement;
    };
    interface HTMLBiggiveHeaderElement extends Components.BiggiveHeader, HTMLStencilElement {
    }
    var HTMLBiggiveHeaderElement: {
        prototype: HTMLBiggiveHeaderElement;
        new (): HTMLBiggiveHeaderElement;
    };
    interface HTMLBiggiveHeadingElement extends Components.BiggiveHeading, HTMLStencilElement {
    }
    var HTMLBiggiveHeadingElement: {
        prototype: HTMLBiggiveHeadingElement;
        new (): HTMLBiggiveHeadingElement;
    };
    interface HTMLBiggiveHeroImageElement extends Components.BiggiveHeroImage, HTMLStencilElement {
    }
    var HTMLBiggiveHeroImageElement: {
        prototype: HTMLBiggiveHeroImageElement;
        new (): HTMLBiggiveHeroImageElement;
    };
    interface HTMLBiggiveIconGroupElement extends Components.BiggiveIconGroup, HTMLStencilElement {
    }
    var HTMLBiggiveIconGroupElement: {
        prototype: HTMLBiggiveIconGroupElement;
        new (): HTMLBiggiveIconGroupElement;
    };
    interface HTMLBiggiveImageElement extends Components.BiggiveImage, HTMLStencilElement {
    }
    var HTMLBiggiveImageElement: {
        prototype: HTMLBiggiveImageElement;
        new (): HTMLBiggiveImageElement;
    };
    interface HTMLBiggiveImageFeatureElement extends Components.BiggiveImageFeature, HTMLStencilElement {
    }
    var HTMLBiggiveImageFeatureElement: {
        prototype: HTMLBiggiveImageFeatureElement;
        new (): HTMLBiggiveImageFeatureElement;
    };
    interface HTMLBiggiveMainMenuElement extends Components.BiggiveMainMenu, HTMLStencilElement {
    }
    var HTMLBiggiveMainMenuElement: {
        prototype: HTMLBiggiveMainMenuElement;
        new (): HTMLBiggiveMainMenuElement;
    };
    interface HTMLBiggiveMiscIconElement extends Components.BiggiveMiscIcon, HTMLStencilElement {
    }
    var HTMLBiggiveMiscIconElement: {
        prototype: HTMLBiggiveMiscIconElement;
        new (): HTMLBiggiveMiscIconElement;
    };
    interface HTMLBiggiveNavGroupElement extends Components.BiggiveNavGroup, HTMLStencilElement {
    }
    var HTMLBiggiveNavGroupElement: {
        prototype: HTMLBiggiveNavGroupElement;
        new (): HTMLBiggiveNavGroupElement;
    };
    interface HTMLBiggiveNavItemElement extends Components.BiggiveNavItem, HTMLStencilElement {
    }
    var HTMLBiggiveNavItemElement: {
        prototype: HTMLBiggiveNavItemElement;
        new (): HTMLBiggiveNavItemElement;
    };
    interface HTMLBiggivePageColumnElement extends Components.BiggivePageColumn, HTMLStencilElement {
    }
    var HTMLBiggivePageColumnElement: {
        prototype: HTMLBiggivePageColumnElement;
        new (): HTMLBiggivePageColumnElement;
    };
    interface HTMLBiggivePageColumnsElement extends Components.BiggivePageColumns, HTMLStencilElement {
    }
    var HTMLBiggivePageColumnsElement: {
        prototype: HTMLBiggivePageColumnsElement;
        new (): HTMLBiggivePageColumnsElement;
    };
    interface HTMLBiggivePageSectionElement extends Components.BiggivePageSection, HTMLStencilElement {
    }
    var HTMLBiggivePageSectionElement: {
        prototype: HTMLBiggivePageSectionElement;
        new (): HTMLBiggivePageSectionElement;
    };
    interface HTMLBiggivePopupElement extends Components.BiggivePopup, HTMLStencilElement {
    }
    var HTMLBiggivePopupElement: {
        prototype: HTMLBiggivePopupElement;
        new (): HTMLBiggivePopupElement;
    };
    interface HTMLBiggivePopupStandaloneElement extends Components.BiggivePopupStandalone, HTMLStencilElement {
    }
    var HTMLBiggivePopupStandaloneElement: {
        prototype: HTMLBiggivePopupStandaloneElement;
        new (): HTMLBiggivePopupStandaloneElement;
    };
    interface HTMLBiggiveProgressBarElement extends Components.BiggiveProgressBar, HTMLStencilElement {
    }
    var HTMLBiggiveProgressBarElement: {
        prototype: HTMLBiggiveProgressBarElement;
        new (): HTMLBiggiveProgressBarElement;
    };
    interface HTMLBiggiveQuoteElement extends Components.BiggiveQuote, HTMLStencilElement {
    }
    var HTMLBiggiveQuoteElement: {
        prototype: HTMLBiggiveQuoteElement;
        new (): HTMLBiggiveQuoteElement;
    };
    /**
     * @deprecated (?) I don't think Donate is using this. Unless there is a WordPress use case,
     * should we delete it rather than maintaining?
     */
    interface HTMLBiggiveSearchElement extends Components.BiggiveSearch, HTMLStencilElement {
    }
    var HTMLBiggiveSearchElement: {
        prototype: HTMLBiggiveSearchElement;
        new (): HTMLBiggiveSearchElement;
    };
    interface HTMLBiggiveSocialIconElement extends Components.BiggiveSocialIcon, HTMLStencilElement {
    }
    var HTMLBiggiveSocialIconElement: {
        prototype: HTMLBiggiveSocialIconElement;
        new (): HTMLBiggiveSocialIconElement;
    };
    interface HTMLBiggiveTabElement extends Components.BiggiveTab, HTMLStencilElement {
    }
    var HTMLBiggiveTabElement: {
        prototype: HTMLBiggiveTabElement;
        new (): HTMLBiggiveTabElement;
    };
    interface HTMLBiggiveTabbedContentElement extends Components.BiggiveTabbedContent, HTMLStencilElement {
    }
    var HTMLBiggiveTabbedContentElement: {
        prototype: HTMLBiggiveTabbedContentElement;
        new (): HTMLBiggiveTabbedContentElement;
    };
    interface HTMLBiggiveTextInputElement extends Components.BiggiveTextInput, HTMLStencilElement {
    }
    var HTMLBiggiveTextInputElement: {
        prototype: HTMLBiggiveTextInputElement;
        new (): HTMLBiggiveTextInputElement;
    };
    interface HTMLBiggiveTotalizerElement extends Components.BiggiveTotalizer, HTMLStencilElement {
    }
    var HTMLBiggiveTotalizerElement: {
        prototype: HTMLBiggiveTotalizerElement;
        new (): HTMLBiggiveTotalizerElement;
    };
    interface HTMLBiggiveTotalizerTickerItemElement extends Components.BiggiveTotalizerTickerItem, HTMLStencilElement {
    }
    var HTMLBiggiveTotalizerTickerItemElement: {
        prototype: HTMLBiggiveTotalizerTickerItemElement;
        new (): HTMLBiggiveTotalizerTickerItemElement;
    };
    interface HTMLBiggiveVideoElement extends Components.BiggiveVideo, HTMLStencilElement {
    }
    var HTMLBiggiveVideoElement: {
        prototype: HTMLBiggiveVideoElement;
        new (): HTMLBiggiveVideoElement;
    };
    interface HTMLBiggiveVideoFeatureElement extends Components.BiggiveVideoFeature, HTMLStencilElement {
    }
    var HTMLBiggiveVideoFeatureElement: {
        prototype: HTMLBiggiveVideoFeatureElement;
        new (): HTMLBiggiveVideoFeatureElement;
    };
    interface HTMLElementTagNameMap {
        "biggive-article-card": HTMLBiggiveArticleCardElement;
        "biggive-back-to-top": HTMLBiggiveBackToTopElement;
        "biggive-basic-card": HTMLBiggiveBasicCardElement;
        "biggive-beneficiary-icon": HTMLBiggiveBeneficiaryIconElement;
        "biggive-biography-card": HTMLBiggiveBiographyCardElement;
        "biggive-boxed-content": HTMLBiggiveBoxedContentElement;
        "biggive-branded-image": HTMLBiggiveBrandedImageElement;
        "biggive-button": HTMLBiggiveButtonElement;
        "biggive-call-to-action": HTMLBiggiveCallToActionElement;
        "biggive-campaign-card": HTMLBiggiveCampaignCardElement;
        "biggive-campaign-card-filter-grid": HTMLBiggiveCampaignCardFilterGridElement;
        "biggive-campaign-highlights": HTMLBiggiveCampaignHighlightsElement;
        "biggive-category-icon": HTMLBiggiveCategoryIconElement;
        "biggive-footer": HTMLBiggiveFooterElement;
        "biggive-form": HTMLBiggiveFormElement;
        "biggive-form-field-select": HTMLBiggiveFormFieldSelectElement;
        "biggive-form-field-select-option": HTMLBiggiveFormFieldSelectOptionElement;
        "biggive-formatted-text": HTMLBiggiveFormattedTextElement;
        "biggive-grid": HTMLBiggiveGridElement;
        "biggive-header": HTMLBiggiveHeaderElement;
        "biggive-heading": HTMLBiggiveHeadingElement;
        "biggive-hero-image": HTMLBiggiveHeroImageElement;
        "biggive-icon-group": HTMLBiggiveIconGroupElement;
        "biggive-image": HTMLBiggiveImageElement;
        "biggive-image-feature": HTMLBiggiveImageFeatureElement;
        "biggive-main-menu": HTMLBiggiveMainMenuElement;
        "biggive-misc-icon": HTMLBiggiveMiscIconElement;
        "biggive-nav-group": HTMLBiggiveNavGroupElement;
        "biggive-nav-item": HTMLBiggiveNavItemElement;
        "biggive-page-column": HTMLBiggivePageColumnElement;
        "biggive-page-columns": HTMLBiggivePageColumnsElement;
        "biggive-page-section": HTMLBiggivePageSectionElement;
        "biggive-popup": HTMLBiggivePopupElement;
        "biggive-popup-standalone": HTMLBiggivePopupStandaloneElement;
        "biggive-progress-bar": HTMLBiggiveProgressBarElement;
        "biggive-quote": HTMLBiggiveQuoteElement;
        "biggive-search": HTMLBiggiveSearchElement;
        "biggive-social-icon": HTMLBiggiveSocialIconElement;
        "biggive-tab": HTMLBiggiveTabElement;
        "biggive-tabbed-content": HTMLBiggiveTabbedContentElement;
        "biggive-text-input": HTMLBiggiveTextInputElement;
        "biggive-totalizer": HTMLBiggiveTotalizerElement;
        "biggive-totalizer-ticker-item": HTMLBiggiveTotalizerTickerItemElement;
        "biggive-video": HTMLBiggiveVideoElement;
        "biggive-video-feature": HTMLBiggiveVideoFeatureElement;
    }
}
declare namespace LocalJSX {
    interface BiggiveArticleCard {
        /**
          * Card background colour
         */
        "backgroundColour"?: string;
        /**
          * Card background colour hover
         */
        "backgroundColourHover"?: string;
        /**
          * Button label
         */
        "buttonLabel"?: string;
        /**
          * Button URL
         */
        "buttonUrl"?: string;
        /**
          * Date
         */
        "date"?: string;
        /**
          * Image Alt Text
         */
        "imageAltText"?: string;
        /**
          * Image Label
         */
        "imageLabel"?: string;
        /**
          * Image URL
         */
        "imageUrl"?: string;
        /**
          * Main title
         */
        "mainTitle"?: string;
        /**
          * Slug
         */
        "slug"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Text colour
         */
        "textColour"?: string;
    }
    interface BiggiveBackToTop {
    }
    interface BiggiveBasicCard {
        /**
          * Background colour.
         */
        "backgroundColour"?: string;
        /**
          * Full URL of the background image.
         */
        "backgroundImageUrl"?: string;
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme"?: string;
        /**
          * Button label
         */
        "buttonLabel"?: string;
        /**
          * Button URL
         */
        "buttonUrl"?: string;
        /**
          * Card colour
         */
        "cardColour"?: string;
        /**
          * Clip bottom left corner
         */
        "clipBottomLeftCorner"?: boolean;
        /**
          * Clip top right corner
         */
        "clipTopRightCorner"?: boolean;
        "headingLevel"?: 1 | 2 | 3 | 4 | 5 | 6;
        /**
          * Icon
         */
        "icon"?: boolean;
        /**
          * Icon colour
         */
        "iconColour"?: string;
        /**
          * Main title
         */
        "mainTitle"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Subtitle title
         */
        "subtitle"?: string;
        /**
          * Teaser
         */
        "teaser"?: string;
        /**
          * Text colour
         */
        "textColour"?: string;
    }
    interface BiggiveBeneficiaryIcon {
        /**
          * Background colour
         */
        "backgroundColour"?: string;
        /**
          * Icon
         */
        "icon"?: string;
        /**
          * Background colour
         */
        "iconColour"?: string;
        /**
          * Label
         */
        "label"?: string;
        /**
          * Url
         */
        "url"?: string;
    }
    interface BiggiveBiographyCard {
        /**
          * Job title
         */
        "fullName"?: string;
        /**
          * Full URL of the main image.
         */
        "imageUrl"?: string;
        /**
          * Job title
         */
        "jobTitle"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveBoxedContent {
        /**
          * Background colour
         */
        "backgroundColour"?: string;
        /**
          * Horizontal padding
         */
        "horizontalPadding"?: number;
        /**
          * Shadow
         */
        "shadow"?: boolean;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Vertical padding
         */
        "verticalPadding"?: number;
    }
    interface BiggiveBrandedImage {
        /**
          * Charity location
         */
        "charityLocation"?: string;
        /**
          * Charity name
         */
        "charityName"?: string;
        /**
          * Link to the charity's website
         */
        "charityUrl"?: string;
        /**
          * Full URL of a image.
         */
        "imageUrl"?: string;
        /**
          * Full URL of the logo.
         */
        "logoUrl"?: string;
        /**
          * Slug
         */
        "slug"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveButton {
        /**
          * Centered
         */
        "centered"?: boolean;
        /**
          * Colour Scheme
         */
        "colourScheme"?: string;
        /**
          * Display full width
         */
        "fullWidth"?: boolean;
        /**
          * Text
         */
        "label"?: string;
        "onDoButtonClick"?: (event: BiggiveButtonCustomEvent<{ event: object; url: string }>) => void;
        /**
          * New Tab
         */
        "openInNewTab"?: boolean;
        /**
          * Rounded corners
         */
        "rounded"?: boolean;
        /**
          * Size
         */
        "size"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * URL
         */
        "url"?: string;
    }
    interface BiggiveCallToAction {
        /**
          * Default text colour
         */
        "defaultTextColour"?: string;
        /**
          * Main title
         */
        "mainTitle"?: string;
        /**
          * Main title colour
         */
        "mainTitleColour"?: string;
        /**
          * Main title size
         */
        "mainTitleSize"?: number;
        /**
          * Primary button Colour Scheme
         */
        "primaryButtonColourScheme"?: string;
        /**
          * Primary button Label
         */
        "primaryButtonLabel"?: string;
        /**
          * Primary button Url
         */
        "primaryButtonUrl"?: string;
        /**
          * Secondary button Colour Scheme
         */
        "secondaryButtonColourScheme"?: string;
        /**
          * Secondary button Label
         */
        "secondaryButtonLabel"?: string;
        /**
          * Secondary button Url
         */
        "secondaryButtonUrl"?: string;
        /**
          * Slug
         */
        "slug"?: string;
        /**
          * Slug colour
         */
        "slugColour"?: string;
        /**
          * Slug size
         */
        "slugSize"?: number;
        /**
          * Space above component
         */
        "spaceAbove"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Subtitle
         */
        "subtitle"?: string;
        /**
          * Subtitle colour
         */
        "subtitleColour"?: string;
        /**
          * Main title size
         */
        "subtitleSize"?: number;
        /**
          * Teaser
         */
        "teaser"?: string;
        /**
          * Teaser colour
         */
        "teaserColour"?: string;
    }
    interface BiggiveCampaignCard {
        /**
          * Full URL of a banner image.
         */
        "banner"?: string;
        /**
          * Display name of the charity's specific time-bound fundraising campaign.
         */
        "campaignTitle"?: string;
        /**
          * e.g. "Match Funded".
         */
        "campaignType"?: string;
        /**
          * To be used alongside isFutureCampaign = true or isPastCampaign = true. If either is true, we render out: 'Launches: ' + datetime or 'Closed: ' + datetime. Preferred format: DD/MM/YYYY, HH:MM DON-661.
         */
        "datetime"?: string;
        /**
          * Donate button colour scheme
         */
        "donateButtonColourScheme"?: string;
        /**
          * Donate button label
         */
        "donateButtonLabel"?: string;
        /**
          * Donate button url
         */
        "donateButtonUrl"?: string;
        /**
          * Boolean flag telling the component if the campaign is in the future (not open yet).
         */
        "isFutureCampaign"?: boolean;
        /**
          * Boolean flag telling the component if the campaign is in the future (not open yet).
         */
        "isPastCampaign"?: boolean;
        /**
          * Donate button colour scheme
         */
        "moreInfoButtonColourScheme"?: string;
        /**
          * More information button label
         */
        "moreInfoButtonLabel"?: string;
        /**
          * More information button url
         */
        "moreInfoButtonUrl"?: string;
        "onDoCardGeneralClick"?: (event: BiggiveCampaignCardCustomEvent<{ event: object; url: string }>) => void;
        /**
          * Display name of the charity or non-profit.
         */
        "organisationName"?: string;
        /**
          * Amount for the primary figure, formatted with currency symbol
         */
        "primaryFigureAmount"?: string;
        /**
          * Label for the primary figure
         */
        "primaryFigureLabel"?: string;
        /**
          * Progress bar percentage
         */
        "progressBarCounter"?: number;
        /**
          * Amount for the secondary figure, formatted with currency symbol
         */
        "secondaryFigureAmount"?: string;
        /**
          * Label for the secondary figure
         */
        "secondaryFigureLabel"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveCampaignCardFilterGrid {
        /**
          * JSON array of beneficiary key/values, or takes a stringified equiavalent (for Storybook)
         */
        "beneficiaryOptions"?: string | string[];
        /**
          * Defines the text on the search button
         */
        "buttonText"?: string;
        /**
          * JSON array of category key/values, or takes a stringified equiavalent (for Storybook)
         */
        "categoryOptions"?: string | string[];
        /**
          * JSON array of funding key/values, or takes a stringified equiavalent (for Storybook)
         */
        "fundingOptions"?: string | string[];
        /**
          * Intro
         */
        "intro"?: string;
        /**
          * JSON array of location key/values, or takes a stringified equiavalent (for Storybook)
         */
        "locationOptions"?: string | string[];
        /**
          * This event `doSearchAndFilterUpdate` event is emitted and propogates to the parent component which handles it
         */
        "onDoSearchAndFilterUpdate"?: (event: BiggiveCampaignCardFilterGridCustomEvent<{
    searchText: string | null;
    sortBy: string | null;
    filterCategory: string | null;
    filterBeneficiary: string | null;
    filterLocation: string | null;
    filterFunding: string | null;
  }>) => void;
        /**
          * Defines the text displayed as the placeholder in the input field before the user types anything
         */
        "placeholderText"?: string;
        /**
          * Optional search text prop. Useful for pre-populating the search field when the page is loaded with a search term already existing in the URL. This can happen when sharing links, or if a donor goes to a campaign page after searching, and then returns to the search results. In such a case, the search box text will clear, unless we use this prop to populate it on rendering. DON-652.
         */
        "searchText"?: string | null;
        /**
          * For injecting the chosen beneficiary to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterBeneficiary"?: string | null;
        /**
          * For injecting the chosen category to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterCategory"?: string | null;
        /**
          * For injecting the chosen funding to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterFunding"?: string | null;
        /**
          * For injecting the chosen location to filter by, as per the comment above for `selectedSortByOption`.
         */
        "selectedFilterLocation"?: string | null;
        /**
          * This helps us inject a pre-selected dropdown value from outside of this component. This is especially helpful for the Meta campaign and Explore pages, where searching by text whipes out previous sort options and re-uses Relevance, or where one of those two pages is loaded directly with URL parameters - in such a scenario the dropdown shows that it's pre-selected. DON-558.
         */
        "selectedSortByOption"?: 'Most raised' | 'Match funds remaining' | 'Relevance' | null;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveCampaignHighlights {
        /**
          * Full URL of a banner image.
         */
        "banner"?: string;
        /**
          * Display name of the charity's specific time-bound fundraising campaign.
         */
        "campaignTitle"?: string;
        /**
          * Champion's name
         */
        "championName"?: string;
        /**
          * Link to all meta-campaigns funded by this champion. For example: /christmas-challenge-2022/the-reed-foundation-22 In other words, it follows the following format: '/' + campaign.parentRef + '/' + campaign.championRef
         */
        "championUrl"?: string;
        /**
          * Amount for the primary figure, formatted with currency symbol
         */
        "primaryFigureAmount"?: string;
        /**
          * Label for the primary figure
         */
        "primaryFigureLabel"?: string;
        /**
          * Primary stat icon
         */
        "primaryStatIcon"?: string;
        /**
          * Primary stat text
         */
        "primaryStatText"?: string;
        /**
          * Progress bar percentage
         */
        "progressBarCounter"?: number;
        /**
          * Amount for the secondary figure, formatted with currency symbol
         */
        "secondaryFigureAmount"?: string;
        /**
          * Label for the secondary figure
         */
        "secondaryFigureLabel"?: string;
        /**
          * Secondary stat icon
         */
        "secondaryStatIcon"?: string;
        /**
          * Secondary stat text
         */
        "secondaryStatText"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveCategoryIcon {
        /**
          * Background colour
         */
        "backgroundColour"?: string;
        /**
          * Icon
         */
        "icon"?: string;
        /**
          * Background colour
         */
        "iconColour"?: string;
        /**
          * Label
         */
        "label"?: string;
        /**
          * Url
         */
        "url"?: string;
    }
    interface BiggiveFooter {
        "headingLevel"?: 1 | 2 | 3 | 4 | 5 | 6;
    }
    interface BiggiveForm {
    }
    interface BiggiveFormFieldSelect {
        /**
          * This event `doChange` event is emitted and propogates to the parent component which handles it
         */
        "onDoSelectChange"?: (event: BiggiveFormFieldSelectCustomEvent<object>) => void;
        /**
          * Placeholder
         */
        "placeholder"?: string;
        "selectedLabel"?: string | null;
        "selectedValue"?: string | null;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveFormFieldSelectOption {
        /**
          * Label
         */
        "label"?: string;
        /**
          * This event `doOptionSelect` event is emitted and propogates to the parent component which handles it
         */
        "onDoOptionSelect"?: (event: BiggiveFormFieldSelectOptionCustomEvent<object>) => void;
        /**
          * Value
         */
        "value"?: string;
    }
    interface BiggiveFormattedText {
        /**
          * Default text colour
         */
        "defaultTextColour"?: string;
        /**
          * Width
         */
        "maxWidth"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveGrid {
        /**
          * Number of columns in grid
         */
        "columnCount"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Should have `justify-content: space-between`?
         */
        "spaceBetween"?: boolean;
    }
    interface BiggiveHeader {
        /**
          * Logo hyperlink URL
         */
        "logoUrl"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveHeading {
        /**
          * Text alignment
         */
        "align"?: string;
        /**
          * Colour Scheme
         */
        "colour"?: string;
        /**
          * HTML element
         */
        "htmlElement"?: string;
        /**
          * Icon
         */
        "icon"?: boolean;
        /**
          * Icon colour
         */
        "iconColour"?: string;
        /**
          * Heading size
         */
        "size"?: number;
        /**
          * Space above component
         */
        "spaceAbove"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Heading text
         */
        "text"?: string;
    }
    interface BiggiveHeroImage {
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme"?: string;
        /**
          * Button Label
         */
        "buttonLabel"?: string;
        /**
          * Button Url
         */
        "buttonUrl"?: string;
        /**
          * Colour Scheme
         */
        "colourScheme"?: string;
        /**
          * Full URL of a logo image.
         */
        "logo"?: string;
        /**
          * Logo alt text
         */
        "logoAltText"?: string;
        /**
          * Full URL of a main hero image.
         */
        "mainImage"?: string|null;
        /**
          * Horizontal alignment of image
         */
        "mainImageAlignHorizontal"?: string;
        /**
          * Vertical alignment of image
         */
        "mainImageAlignVertical"?: string;
        /**
          * Hero image title, typically the page.
         */
        "mainTitle"?: string;
        /**
          * Main title colour
         */
        "mainTitleColour"?: string;
        /**
          * Header slug
         */
        "slug"?: string;
        /**
          * Header slug colour
         */
        "slugColour"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Introductory teaser text
         */
        "teaser"?: string;
        /**
          * Teaser colour
         */
        "teaserColour"?: string;
    }
    interface BiggiveIconGroup {
        /**
          * Label
         */
        "label"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveImage {
        /**
          * Image width
         */
        "height"?: number;
        /**
          * Image alt text tag.
         */
        "imageAltText"?: string;
        /**
          * Full URL of a image.
         */
        "imageUrl"?: string;
        /**
          * Size unit
         */
        "sizeUnit"?: string;
        /**
          * Space above component
         */
        "spaceAbove"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Image width
         */
        "width"?: number;
    }
    interface BiggiveImageFeature {
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme"?: string;
        /**
          * Button Label
         */
        "buttonLabel"?: string;
        /**
          * Button Url
         */
        "buttonUrl"?: string;
        /**
          * Default text colour
         */
        "defaultTextColour"?: string;
        /**
          * Image alt text tag.
         */
        "imageAltText"?: string;
        /**
          * Full URL of a image.
         */
        "imageUrl"?: string;
        /**
          * Video title
         */
        "mainTitle"?: string;
        /**
          * Slug colour
         */
        "mainTitleColour"?: string;
        /**
          * Slug
         */
        "slug"?: string;
        /**
          * Slug colour
         */
        "slugColour"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Introductory teaser text
         */
        "teaser"?: string;
        /**
          * Teaser colour
         */
        "teaserColour"?: string;
    }
    interface BiggiveMainMenu {
    }
    interface BiggiveMiscIcon {
        /**
          * Background colour
         */
        "backgroundColour"?: string;
        /**
          * Icon
         */
        "icon"?: string;
        /**
          * Background colour
         */
        "iconColour"?: string;
        /**
          * Url
         */
        "url"?: string;
    }
    interface BiggiveNavGroup {
        /**
          * Inline
         */
        "inline"?: boolean;
    }
    interface BiggiveNavItem {
        /**
          * URL
         */
        "iconColour"?: string;
        /**
          * Label
         */
        "label"?: string;
        /**
          * URL
         */
        "url"?: string;
    }
    interface BiggivePageColumn {
    }
    interface BiggivePageColumns {
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggivePageSection {
        /**
          * Colour scheme
         */
        "colourScheme"?: string;
        /**
          * Width
         */
        "maxWidth"?: number;
        /**
          * Section style bottom
         */
        "sectionStyleBottom"?: string;
        /**
          * Section style top
         */
        "sectionStyleTop"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggivePopup {
    }
    interface BiggivePopupStandalone {
    }
    interface BiggiveProgressBar {
        /**
          * Colour Scheme
         */
        "colourScheme"?: string;
        /**
          * Percentage to show + use for CSS width; round before input if desired
         */
        "counter"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveQuote {
        /**
          * Attribution text
         */
        "attribution"?: string;
        /**
          * Default text colour
         */
        "defaultTextColour"?: string;
        /**
          * Quote text
         */
        "quote"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    /**
     * @deprecated (?) I don't think Donate is using this. Unless there is a WordPress use case,
     * should we delete it rather than maintaining?
     */
    interface BiggiveSearch {
        /**
          * Defines the text on the search button
         */
        "buttonText"?: string;
        /**
          * This event `doSearch` event is emitted and propogates to the parent component which handles it
         */
        "onDoSearch"?: (event: BiggiveSearchCustomEvent<string>) => void;
        /**
          * Defines the text displayed as the placeholder in the input field before the user types anything
         */
        "placeholderText"?: string;
        "searchText"?: string;
    }
    interface BiggiveSocialIcon {
        /**
          * Background colour
         */
        "backgroundColour"?: string;
        /**
          * Icon colour
         */
        "iconColour"?: string;
        /**
          * Service name
         */
        "service"?: string;
        /**
          * Url
         */
        "url"?: string;
    }
    interface BiggiveTab {
        /**
          * Title
         */
        "tabTitle"?: string;
    }
    interface BiggiveTabbedContent {
        /**
          * Default text colour
         */
        "defaultTextColour"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveTextInput {
    }
    interface BiggiveTotalizer {
        /**
          * Primary message
         */
        "mainMessage"?: string;
        /**
          * Primary banner colour
         */
        "primaryColour"?: string;
        /**
          * Primary text colour
         */
        "primaryTextColour"?: string;
        /**
          * Secondary banner colour
         */
        "secondaryColour"?: string;
        /**
          * Secondary text colour
         */
        "secondaryTextColour"?: string;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
    }
    interface BiggiveTotalizerTickerItem {
        /**
          * Figure
         */
        "figure"?: string;
        /**
          * Figure
         */
        "label"?: string;
    }
    interface BiggiveVideo {
        /**
          * Space above component
         */
        "spaceAbove"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Full URL of a video.
         */
        "videoUrl"?: string;
    }
    interface BiggiveVideoFeature {
        /**
          * Button Colour Scheme
         */
        "buttonColourScheme"?: string;
        /**
          * Button Label
         */
        "buttonLabel"?: string;
        /**
          * Button Url
         */
        "buttonUrl"?: string;
        /**
          * Default text colour
         */
        "defaultTextColour"?: string;
        /**
          * Video title
         */
        "mainTitle"?: string;
        /**
          * Slug colour
         */
        "mainTitleColour"?: string;
        /**
          * Slug
         */
        "slug"?: string;
        /**
          * Slug colour
         */
        "slugColour"?: string;
        /**
          * Space above component
         */
        "spaceAbove"?: number;
        /**
          * Space below component
         */
        "spaceBelow"?: number;
        /**
          * Introductory teaser text
         */
        "teaser"?: string;
        /**
          * Teaser colour
         */
        "teaserColour"?: string;
        /**
          * Full URL of a video.
         */
        "videoUrl"?: string;
    }
    interface IntrinsicElements {
        "biggive-article-card": BiggiveArticleCard;
        "biggive-back-to-top": BiggiveBackToTop;
        "biggive-basic-card": BiggiveBasicCard;
        "biggive-beneficiary-icon": BiggiveBeneficiaryIcon;
        "biggive-biography-card": BiggiveBiographyCard;
        "biggive-boxed-content": BiggiveBoxedContent;
        "biggive-branded-image": BiggiveBrandedImage;
        "biggive-button": BiggiveButton;
        "biggive-call-to-action": BiggiveCallToAction;
        "biggive-campaign-card": BiggiveCampaignCard;
        "biggive-campaign-card-filter-grid": BiggiveCampaignCardFilterGrid;
        "biggive-campaign-highlights": BiggiveCampaignHighlights;
        "biggive-category-icon": BiggiveCategoryIcon;
        "biggive-footer": BiggiveFooter;
        "biggive-form": BiggiveForm;
        "biggive-form-field-select": BiggiveFormFieldSelect;
        "biggive-form-field-select-option": BiggiveFormFieldSelectOption;
        "biggive-formatted-text": BiggiveFormattedText;
        "biggive-grid": BiggiveGrid;
        "biggive-header": BiggiveHeader;
        "biggive-heading": BiggiveHeading;
        "biggive-hero-image": BiggiveHeroImage;
        "biggive-icon-group": BiggiveIconGroup;
        "biggive-image": BiggiveImage;
        "biggive-image-feature": BiggiveImageFeature;
        "biggive-main-menu": BiggiveMainMenu;
        "biggive-misc-icon": BiggiveMiscIcon;
        "biggive-nav-group": BiggiveNavGroup;
        "biggive-nav-item": BiggiveNavItem;
        "biggive-page-column": BiggivePageColumn;
        "biggive-page-columns": BiggivePageColumns;
        "biggive-page-section": BiggivePageSection;
        "biggive-popup": BiggivePopup;
        "biggive-popup-standalone": BiggivePopupStandalone;
        "biggive-progress-bar": BiggiveProgressBar;
        "biggive-quote": BiggiveQuote;
        "biggive-search": BiggiveSearch;
        "biggive-social-icon": BiggiveSocialIcon;
        "biggive-tab": BiggiveTab;
        "biggive-tabbed-content": BiggiveTabbedContent;
        "biggive-text-input": BiggiveTextInput;
        "biggive-totalizer": BiggiveTotalizer;
        "biggive-totalizer-ticker-item": BiggiveTotalizerTickerItem;
        "biggive-video": BiggiveVideo;
        "biggive-video-feature": BiggiveVideoFeature;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "biggive-article-card": LocalJSX.BiggiveArticleCard & JSXBase.HTMLAttributes<HTMLBiggiveArticleCardElement>;
            "biggive-back-to-top": LocalJSX.BiggiveBackToTop & JSXBase.HTMLAttributes<HTMLBiggiveBackToTopElement>;
            "biggive-basic-card": LocalJSX.BiggiveBasicCard & JSXBase.HTMLAttributes<HTMLBiggiveBasicCardElement>;
            "biggive-beneficiary-icon": LocalJSX.BiggiveBeneficiaryIcon & JSXBase.HTMLAttributes<HTMLBiggiveBeneficiaryIconElement>;
            "biggive-biography-card": LocalJSX.BiggiveBiographyCard & JSXBase.HTMLAttributes<HTMLBiggiveBiographyCardElement>;
            "biggive-boxed-content": LocalJSX.BiggiveBoxedContent & JSXBase.HTMLAttributes<HTMLBiggiveBoxedContentElement>;
            "biggive-branded-image": LocalJSX.BiggiveBrandedImage & JSXBase.HTMLAttributes<HTMLBiggiveBrandedImageElement>;
            "biggive-button": LocalJSX.BiggiveButton & JSXBase.HTMLAttributes<HTMLBiggiveButtonElement>;
            "biggive-call-to-action": LocalJSX.BiggiveCallToAction & JSXBase.HTMLAttributes<HTMLBiggiveCallToActionElement>;
            "biggive-campaign-card": LocalJSX.BiggiveCampaignCard & JSXBase.HTMLAttributes<HTMLBiggiveCampaignCardElement>;
            "biggive-campaign-card-filter-grid": LocalJSX.BiggiveCampaignCardFilterGrid & JSXBase.HTMLAttributes<HTMLBiggiveCampaignCardFilterGridElement>;
            "biggive-campaign-highlights": LocalJSX.BiggiveCampaignHighlights & JSXBase.HTMLAttributes<HTMLBiggiveCampaignHighlightsElement>;
            "biggive-category-icon": LocalJSX.BiggiveCategoryIcon & JSXBase.HTMLAttributes<HTMLBiggiveCategoryIconElement>;
            "biggive-footer": LocalJSX.BiggiveFooter & JSXBase.HTMLAttributes<HTMLBiggiveFooterElement>;
            "biggive-form": LocalJSX.BiggiveForm & JSXBase.HTMLAttributes<HTMLBiggiveFormElement>;
            "biggive-form-field-select": LocalJSX.BiggiveFormFieldSelect & JSXBase.HTMLAttributes<HTMLBiggiveFormFieldSelectElement>;
            "biggive-form-field-select-option": LocalJSX.BiggiveFormFieldSelectOption & JSXBase.HTMLAttributes<HTMLBiggiveFormFieldSelectOptionElement>;
            "biggive-formatted-text": LocalJSX.BiggiveFormattedText & JSXBase.HTMLAttributes<HTMLBiggiveFormattedTextElement>;
            "biggive-grid": LocalJSX.BiggiveGrid & JSXBase.HTMLAttributes<HTMLBiggiveGridElement>;
            "biggive-header": LocalJSX.BiggiveHeader & JSXBase.HTMLAttributes<HTMLBiggiveHeaderElement>;
            "biggive-heading": LocalJSX.BiggiveHeading & JSXBase.HTMLAttributes<HTMLBiggiveHeadingElement>;
            "biggive-hero-image": LocalJSX.BiggiveHeroImage & JSXBase.HTMLAttributes<HTMLBiggiveHeroImageElement>;
            "biggive-icon-group": LocalJSX.BiggiveIconGroup & JSXBase.HTMLAttributes<HTMLBiggiveIconGroupElement>;
            "biggive-image": LocalJSX.BiggiveImage & JSXBase.HTMLAttributes<HTMLBiggiveImageElement>;
            "biggive-image-feature": LocalJSX.BiggiveImageFeature & JSXBase.HTMLAttributes<HTMLBiggiveImageFeatureElement>;
            "biggive-main-menu": LocalJSX.BiggiveMainMenu & JSXBase.HTMLAttributes<HTMLBiggiveMainMenuElement>;
            "biggive-misc-icon": LocalJSX.BiggiveMiscIcon & JSXBase.HTMLAttributes<HTMLBiggiveMiscIconElement>;
            "biggive-nav-group": LocalJSX.BiggiveNavGroup & JSXBase.HTMLAttributes<HTMLBiggiveNavGroupElement>;
            "biggive-nav-item": LocalJSX.BiggiveNavItem & JSXBase.HTMLAttributes<HTMLBiggiveNavItemElement>;
            "biggive-page-column": LocalJSX.BiggivePageColumn & JSXBase.HTMLAttributes<HTMLBiggivePageColumnElement>;
            "biggive-page-columns": LocalJSX.BiggivePageColumns & JSXBase.HTMLAttributes<HTMLBiggivePageColumnsElement>;
            "biggive-page-section": LocalJSX.BiggivePageSection & JSXBase.HTMLAttributes<HTMLBiggivePageSectionElement>;
            "biggive-popup": LocalJSX.BiggivePopup & JSXBase.HTMLAttributes<HTMLBiggivePopupElement>;
            "biggive-popup-standalone": LocalJSX.BiggivePopupStandalone & JSXBase.HTMLAttributes<HTMLBiggivePopupStandaloneElement>;
            "biggive-progress-bar": LocalJSX.BiggiveProgressBar & JSXBase.HTMLAttributes<HTMLBiggiveProgressBarElement>;
            "biggive-quote": LocalJSX.BiggiveQuote & JSXBase.HTMLAttributes<HTMLBiggiveQuoteElement>;
            /**
             * @deprecated (?) I don't think Donate is using this. Unless there is a WordPress use case,
             * should we delete it rather than maintaining?
             */
            "biggive-search": LocalJSX.BiggiveSearch & JSXBase.HTMLAttributes<HTMLBiggiveSearchElement>;
            "biggive-social-icon": LocalJSX.BiggiveSocialIcon & JSXBase.HTMLAttributes<HTMLBiggiveSocialIconElement>;
            "biggive-tab": LocalJSX.BiggiveTab & JSXBase.HTMLAttributes<HTMLBiggiveTabElement>;
            "biggive-tabbed-content": LocalJSX.BiggiveTabbedContent & JSXBase.HTMLAttributes<HTMLBiggiveTabbedContentElement>;
            "biggive-text-input": LocalJSX.BiggiveTextInput & JSXBase.HTMLAttributes<HTMLBiggiveTextInputElement>;
            "biggive-totalizer": LocalJSX.BiggiveTotalizer & JSXBase.HTMLAttributes<HTMLBiggiveTotalizerElement>;
            "biggive-totalizer-ticker-item": LocalJSX.BiggiveTotalizerTickerItem & JSXBase.HTMLAttributes<HTMLBiggiveTotalizerTickerItemElement>;
            "biggive-video": LocalJSX.BiggiveVideo & JSXBase.HTMLAttributes<HTMLBiggiveVideoElement>;
            "biggive-video-feature": LocalJSX.BiggiveVideoFeature & JSXBase.HTMLAttributes<HTMLBiggiveVideoFeatureElement>;
        }
    }
}
